apiVersion: v1
kind: Secret
metadata:
    name: yt-watcher-secret
type: Opaque
stringData:
    YOUTUBE_API_KEY: ENC[AES256_GCM,data:iiTUs/k5Q628S6lFFkLstGSpWj2S1BGeTJ5Sor/lPJfnSeMa//vw,iv:TPfB8jrsuE9mu0aRbQQUhqEnzLGmY2TFgfEH1He4Pe0=,tag:3nCtybBJw5+YRIG7+0JVPQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:DFmKf6VlaUmp0cwW2BWg57jqNS0F8J4SV6+yPlza3xwZxRlEH5rnFYR0OzNoJRPk20XozNfJsu0cXKoUNE8=,iv:oTCb6tvo167t8ZObhHNWuY6DKfZFwxzCeV92uz5g1KU=,tag:dRFttVdJgEqWGTuKQMy9rw==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:Q9+4a8HeTD/gAPCv7d49hSCQhJKNTKN5zntmj11Bw78weuZpoePMJHlp7otpRQ==,iv:l+lWZ4AhzA00SFTP6Qldr3oSmTSDr/tlMvAhBNKHzUo=,tag:i/NxD8V+MnjvlCOsdW6Ctw==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:6lTmFI4jpzMj,iv:6EQS2un9gAgmwNaJw4oPsYWLgToFyXDL06vS3QQvVCI=,tag:svUDVAOvWRW2RB3ciho18g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiLzdJYVIwYmF2TWR0Wkpa
            MitlVVI2YzdBTEMwbGFhcndBR3c3YTZZSDFVCisyTWc3dXpkSGw0elUzZzZCRWVk
            UXRPQVR1RnVOamJRM1pIMXUrSTd6MkEKLS0tIFR1b0FCUmhaL3BIelp2NjZzc2ZF
            dVhKSlo4anpMU3R2TkF0ZWp4S2YvcGcK1tEY5mxu5yHd8LS03u+YbKggzKQSrULN
            rr3QOy/9CkBbc88lr4q3WefiScrixtLF4CobPzx562VHp2XGCrfxUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dac76czm4qzf9zcu28gejp3x6t77knx798ms5ew86z97yp38laqskhzzze
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-22T08:37:59Z"
    mac: ENC[AES256_GCM,data:NxYA9fqEKt89KeOHM68CUGjRcNBI9KpkwVtPzZESZ+Dg4hsjhSOtj64Mpkq5BJFneDSyDG5eZC32Ozaf1yMMzSx2A7aXOH40DlzHDJaTHW4h74SlIbFgHVzXoZkPe2ZgwpEoUqnIDa+7ZO9rYZ4BmXU+xhw9+4eCIQYvNPDO+nA=,iv:O7xl94IUp3Wj12iyX4KZ/5JbHhrexip0rm2OmOq1d2c=,tag:MdhgoQ+6Okic1ZmB4SAeLA==,type:str]
    version: 3.13.1
