apiVersion: v1
kind: Secret
metadata:
    name: yt-watcher-secret
type: Opaque
stringData:
    YOUTUBE_API_KEY: ENC[AES256_GCM,data:BjjRfKjyqe7svPPE/OEGpLU91Z4u4nq2Po9D0KJhiYANYdeVP0bB,iv:sNRdYVMCNi4s/35PTvpeny2IwoOIr54/lM8Nw6O+BlA=,tag:zXJCR4Fmd8JgRe4bQmJ4cw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:stL8ySpXY2hUXSN5Pa1cq+TvsuCKVQjWZ/tHGb/mdcbN/oFT4yHLakKI7tXyD7lcCMm3f6dMd1X9QVzbs2I=,iv:G+d1DD9eFgeZqu9PlnGHkqEf6vR+3Di+d0pYPkTEdZY=,tag:RQxQi46QzSLk3E9bLeLVRg==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:8xDYUmxiQAvRpUMRorcoU1KsENUm8fdakYek8J25c8CeUE5oSTeJM4mFvKho1Q==,iv:+cDN/jOf40L2yKqVbK4paTHsNgVLTQQfzjtliu9/HFQ=,tag:YgJ2TBg7OZk3zkArnlBsiA==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:WkqbSQQcXYnu,iv:09vWZOs6PWIiyiO4Myatf8Wa/pH37nXsMiedfwTp/tg=,tag:D65+YBcNXRxoJIK66JPCdQ==,type:int]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSk9vQ2pkZDlRYVFjcXJE
            OW5sR1luVUFYSVRuQ2MvOEZodzhFdUVFYlZvClNCemJXQ3JiNllsSFVEMjlhK2ZQ
            RFpQcC83eXhCMEk0ejl1R0V3ZUNJUHMKLS0tIEtaNzAzUS82S1NQd1ZnL0szeDZu
            UXBEeU8rQ2wwdUVabSt0eUJHOW81QnMKko2HvwNXJsJOPXazZmTaQdWESOvq0uqs
            MkQU1EJJTJ9hNNi1XU2T9b38N2UY0xRBif6+8spyDJwg9qxk0RW6BQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dac76czm4qzf9zcu28gejp3x6t77knx798ms5ew86z97yp38laqskhzzze
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-22T08:24:52Z"
    mac: ENC[AES256_GCM,data:WDJF9UQCFjKZGK9vhNHpZnWh42iRp6eMjD4OzMfvR4B5nwM2z3FUQJWLiMHdQ7CdGIHpOG/cwpgrjqmyKOPk7ywEQ5nBY0PZHJUdQvD3APApvbyWxNnmH5sHn61TZS85EC7T0QH84WRVp+iXx033N8pbhOYjmx5vQ8eEM6/DLjY=,iv:k8qDZkDCGqV1h7V5TT6MItQICHVJbRwVq0Spvn+OtlQ=,tag:mV8ohHZ2EHvipaB9Qotprg==,type:str]
    version: 3.13.1
