apiVersion: ENC[AES256_GCM,data:hJ8=,iv:Rm1PdHW2hU6FvPkdJVJRgWGbf4bKKhnzhpzVJpWMOxE=,tag:mVE5SGk0aWg1Zj5FdWi63A==,type:str]
kind: ENC[AES256_GCM,data:2zi0ge20,iv:McpUqa9SAtxM1YNvPvp7ejo9m/YIxfEjc4rbwxgwLA0=,tag:j2aClg7ZFTm7VaTUiJ7AAQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:fzeQgEVt9bOIuhv8WN4gR2s=,iv:80ilYevghLrTGYUIGubKfviXFk0pY1MvUDlRfiip1rI=,tag:glNKKcYv5NbXmvw2dTDmSg==,type:str]
type: ENC[AES256_GCM,data:5fg0At3J,iv:untQKVkShGlt8oyH1qH+EkYvoKWc4G0itDyA/a2Z/nM=,tag:6eCq7ddlrANPMrGyD08mAA==,type:str]
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:vf6hHa8ZKKCaD8S3ErGP3dnzejL6tdGTs+41jfSR1jYlaB7+DjcrFo/F5On/+zwEY5LoBgpZuLDEBoKudcQ=,iv:2vTenaBLffRYzX4a3KSjDJGqYD3m32TxJaszq75oNts=,tag:PS0qNUj4gDMPy2ZFnPmOFQ==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:WVQWJ4MtIGzDpA==,iv:ezsl7SgG0QM3Z9sN2GIJPsGMWld06IuyySkOlvZrx8k=,tag:W+bArcfvT084JGMBL++79A==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:2gnd1YhzPrIf,iv:eiOpwxbY7NlEHQFnpoJUPR7oZu1akJy2GN04ME1x1IQ=,tag:ewPBi1G5KAOZ+vZAIC0kLQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2V2xZMmdDUSt5VFBneTlR
            SHpyMUhGUlN4WXI5aXFCZS80YTkwTGdVZ1NjCnc5THJuNHljMEJSYVNlQm52U0pP
            ZGNlZzlmZTFCcDVmOUNiMUhZZTZLeFkKLS0tIHlXMHhrMndiVENrbzI5amtmSVlz
            SUJPZHBTeENObW5KbDdaanBNSkpseTAKNkMxMiTSCNv0fgI+WJ0LSg+Vle6VOEkK
            fZ+ANJmCVzqMDW0ca/hmgVGb8xdt+u3VXAGCS+MJxUUSVySPmcwMhA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dac76czm4qzf9zcu28gejp3x6t77knx798ms5ew86z97yp38laqskhzzze
    lastmodified: "2026-05-19T12:15:56Z"
    mac: ENC[AES256_GCM,data:B64nzp/XYN1XEmfv67jPFz+G4vjtzlvlF/WZEGnwZbtNTr/lRD+B6r36lK1ewd2qytyyY/Nom0Px5oyQGCblNsxh1/JWEMWXlYzfbvtj+yaVoZKqRuJO8DcwRfjgZL6wHHotCOzQhoHYJ9MuG1ka/SSFKeC3IRrcdcNSarbYMDg=,iv:b4NbE1uNOSbB272R71VLWStryq75OVFbqRyrDZuoyUI=,tag:MluJjIb/ankg80ZMR4O8xQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
