apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: yt-watcher

resources:
  # Core
  - namespace.yaml
 
 ## Ingress
  - ingress.yaml

  # App
  - app-config.yaml
  #- app-secret.yaml
  - deployment.yaml

  # Postgres
  - postgres-config.yaml
  #- postgres-secret.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml

  # Redis
  - redis-pvc.yaml
  - redis-deployment.yaml
