apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: yt-watcher
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:6EVkPMvFJKE=,iv:AYGqwbmDoxcn9jAKeewxmESsucrWbMfBngqVmDxliwg=,tag:fL4h7PK0iq91lDPS3BepfQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:KD9pEOfm6eg=,iv:pTUh4mYsSVYhG+E6BSWo8nyWFzK9CVqhOyuiJg/FvUI=,tag:SN0rHAj+C4+0PkXZI1eSGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcFdqczFhR3FROGdFWnVk
            MHB0bGtwV2Z2V3JwYStKYS95YlJ1ZGRmakdZCkR1VjZ5dkZVWk9VNm1QeDQ2b3RE
            Q0UxNDN4bitHdmRwQ0I2NHFNTGVEMGsKLS0tIGV2cTNmWWdMbkVLMU05K3ppc2pi
            cU85ODU0QmVwbVBsV3lPTHVKWHEvaFUKn0ThuOaSjK0L1W31TlQJmwV/hZyAOAoY
            NQmywecA+NqcbTR4xxQ3LCqyko27o5gU3gbQchB98dzfqUjxEW0nKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dac76czm4qzf9zcu28gejp3x6t77knx798ms5ew86z97yp38laqskhzzze
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-19T14:28:42Z"
    mac: ENC[AES256_GCM,data:vxxZfA2hazAcf8XDpLrQEQCNC/gletymYEZFeqMvRTXGhTF8o672ekfG2Gfp3oBgQANIgAdHJ/0Awu8wvggvf/XiQhAUieSlNjLOJcT+tR2fjtO+jhlvBEP0oqFv0Zv7923lw9/AMO6U2Ba3we7k8jU0LonYKS1k6CUT60sQ4H8=,iv:uv8JqyNSfUldpYr4c7cOWLTW9CGhsLdX3KM2WrM06oo=,tag:NWQJLnVAWp/U59QJTurRoQ==,type:str]
    version: 3.13.1
