apiVersion: ENC[AES256_GCM,data:lks=,iv:NVTmuyJs9qIWBUmX4HBzA2laniRDHH3mJeh+E4UptRU=,tag:54XQ1Z0BRfSDOkMXvX66Ew==,type:str]
kind: ENC[AES256_GCM,data:n7FHCvxI,iv:vm3CvKE2XliYjE1xq9jTe14OYxT/fAWAKdExqNCxNDA=,tag:8eA9hD6HJ5MqRRlNxNi6Lw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kUEvKbqAiwphCe3AXl8L,iv:lORhKjDjJUZz25K7ON5I/7rYOoWYOc8nxTXqC63z6qQ=,tag:EAukMlLl+U8VjXRl0zdITQ==,type:str]
    namespace: ENC[AES256_GCM,data:uXNdLzIFP847zw==,iv:yyIGJGI9JkVyGhWI4UnZd/Coa2ma4lSmoYpecg9Fbfo=,tag:RLMmO7z6bY3NZOsny5sZEw==,type:str]
type: ENC[AES256_GCM,data:XF/pzZZ2,iv:k6NF2CMZX6GTvwclkizYviIpuM2aBiFAgOD0JOPnyCA=,tag:AkYEbl/gpIcKs7ENdvUt3A==,type:str]
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:qeZvIq+pYgg=,iv:I3TIs/IKjaP4lsgabTHEsuN0bbY63RS4LzPAF0yAshE=,tag:Awih4yMxSI+TmE9TJjyJBg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:TNmrVDOu8+A=,iv:aYLOp1/vFnFDu2jdBGje3RT6ab+/wG/bufWq1ETMVqo=,tag:/Wtj0ysgXejJWVQj24Oudg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SHZHY3QwajUyZXFubnBy
            OWtVaEdVOGh0elFtZGRhTE12SzI3bHBnQm1rCmZlSTUxM3pRVFhxNnV4UzU0dkhs
            YzFIdGZaU1B1RlJmR05OcEpkcUNkaTAKLS0tIEtLbC9XN21kNWFjdkc3cUJhbVBt
            aE5YV1czSFJhVGFWZVo3Tnd3RFVBODAKx3zr0JnNeCO0qgrmQT743mh8dMs7F58S
            3LHumpu1sglAY5eUcbo5AKcxgfH3vLxTXnb1sFUP78Gwp4L19n+8zw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dac76czm4qzf9zcu28gejp3x6t77knx798ms5ew86z97yp38laqskhzzze
    lastmodified: "2026-05-19T12:16:22Z"
    mac: ENC[AES256_GCM,data:/A6dD5SCDgdoE62twaxt4RncQfGocDnQ+xCs3tzutMB2Xsp7hd4kRQc2w/DTKOhTixPpdrWQV7Tb6XekGmyKn6cVO7NovACTbuFplpmyNKwgOp1UTlXxoNJKPcCtGRCzT/iVnipA4G0qSA3J9vCAdTNtfgR94x3Ev/Tc8YEvnJA=,iv:RfP6xQHrOaJ6wexYC+Qw30cwM2U5nU96Vh2QsiI0J20=,tag:nQdYgo8ObUe+S5gEUIBz4g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
