name: CD 

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - feature/**
    paths:
      - "app/**"
      - "Dockerfile"
      - "requirements.txt"



jobs:
  deploy:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest


    permissions:
      contents: write 
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/yt-watcher:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      

      - name: Update deployment image
        run: |
          sed -i "s|image: .*|image: ghcr.io/${{ github.repository_owner }}/yt-watcher:${{ github.sha }}|" yamls/deployment.yaml


      - name: Commit and push manifest changes
        run: |
          git config user.name "yadhukrishnan96"
          git config user.email "yadhuvipenchika@gmail.com"

          git add yamls/deployment.yaml

          git diff --cached --quiet || git commit -m "Update image tag to ${{ github.sha }}"

          git push
