name: CI


on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push: 
    branches:
      - main
      - feature/**

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Output
        run: echo "Test success"
